# Generated by Django 2.2.10 on 2020-04-13 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ingredients', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('portions', models.CharField(max_length=100)),
                ('preparation_mode', models.TextField()),
                ('preparation_time', models.IntegerField()),
            ],
        ),
    ]
